[project]
name = "python-api-railway"
description = "A Python API project using FastAPI and Flask"
env = "python"

[build]
cmd = "pip install -r requirements.txt"

[start]
cmd = "uvicorn src.fastapi_app:app --host 0.0.0.0 --port $PORT"

[deploy]
cmd = "uvicorn src.fastapi_app:app --host 0.0.0.0 --port $PORT"