"""Explicit local-only integration tests. No paid providers or external acquisition."""
import json
import os
import subprocess
import time
from concurrent.futures import ThreadPoolExecutor
from contextlib import contextmanager
from pathlib import Path
from uuid import uuid4

import jwt
import psycopg
import pytest
from fastapi.testclient import TestClient
from psycopg import sql
from psycopg.rows import dict_row
from pydantic import SecretStr

from src.acquisition.models import EvidenceBundle
from src.acquisition.parsing import finalize, fragment, parse_html
from src.analysis.evidence import direct_json_ld
from src.analysis.models import (
    AudioEvidence,
    PipelineError,
    StageUsage,
    TranscriptResult,
    partial,
)
from src.config import Settings
from src.fastapi_app import create_app
from src.imports.models import JobError
from src.imports.policy import policy_hash
from src.imports.session import DurableSession
from src.imports.store import Store
from src.imports.worker import Worker

pytestmark=pytest.mark.skipif(os.environ.get('FOODIEFY_LOCAL_IMPORT_TESTS')!='1',reason='opt-in local Postgres integration')


@pytest.fixture
def local():
    status=json.loads(subprocess.run(['supabase','status','--output','json'],capture_output=True,text=True,check=True).stdout)
    dsn=status['DB_URL']
    assert psycopg.conninfo.conninfo_to_dict(dsn)['host'] in {'localhost','127.0.0.1','::1'}
    users=[uuid4(),uuid4()]
    admin=psycopg.connect(dsn,autocommit=True,row_factory=dict_row)
    original=admin.execute('select * from foodiefy_imports.controls').fetchone()
    for u in users:
        admin.execute('insert into auth.users(id,aud,role,email) values(%s,\'authenticated\',\'authenticated\',%s)',(u,str(u)+'@foodiefy-test.invalid'))
    admin.execute('update foodiefy_imports.controls set enabled=true,paid_enabled=true,visual_enabled=true,worker_concurrency=1,global_usd=5,user_daily_usd=0.5,job_usd=0.1')
    cfg=Settings(APP_ENV='local',IMPORT_DATABASE_URL=SecretStr(dsn),SUPABASE_URL=status['API_URL'],
                 SUPABASE_JWT_SECRET=SecretStr(status['JWT_SECRET']),IMPORT_ALLOW_PAID=True,
                 OPENAI_API_KEY=SecretStr('offline-tests-only'),GEMINI_API_KEY=SecretStr('offline-tests-only'))
    try:
        yield Store(cfg),admin,users,cfg
    finally:
        for u in users:
            admin.execute('delete from auth.users where id=%s',(u,))  # Only UUIDs generated by this fixture.
        columns=list(original)
        admin.execute(sql.SQL('update foodiefy_imports.controls set {}').format(sql.SQL(',').join(sql.SQL('{}=%s').format(sql.Identifier(c)) for c in columns)),[original[c] for c in columns])
        admin.close()


def enqueue(store,owner,cfg,key=None):
    return store.submit(owner,key or str(uuid4()),{'url':'https://example.org/owned-test'},policy_hash(cfg))


def bearer(cfg,user):
    return {'Authorization':'Bearer '+jwt.encode({'sub':str(user),'aud':'authenticated','iss':cfg.SUPABASE_URL+'/auth/v1',
             'role':'authenticated','iat':int(time.time()),'exp':int(time.time())+60},cfg.SUPABASE_JWT_SECRET.get_secret_value(),algorithm='HS256')}


def test_real_api_two_users_idempotency_and_cancel(local):
    store,admin,(a,b),cfg=local
    with TestClient(create_app(cfg)) as client:
        ah= dict(bearer(cfg,a),**{'Idempotency-Key':str(uuid4())})
        response=client.post('/v1/imports',headers=ah,json={'url':'https://example.org/owned-test'})
        assert response.status_code==202,response.json()
        job=response.json()['job_id']
        assert client.post('/v1/imports',headers=ah,json={'url':'https://example.org/owned-test'}).json()['job_id']==job
        assert client.post('/v1/imports',headers=ah,json={'url':'https://example.org/changed'}).status_code==409
        assert client.get('/v1/imports/'+job,headers=bearer(cfg,b)).status_code==404
        assert client.post('/v1/imports/'+job+'/cancel',headers=bearer(cfg,b)).status_code==404
        assert client.get('/v1/imports',headers=bearer(cfg,b)).json()['items']==[]
        assert client.get('/health/ready').status_code==200
        assert client.post('/v1/imports/'+job+'/cancel',headers=ah).json()['status']=='canceled'
        assert client.get('/v1/imports/'+job,headers=ah).json()['stage'] is None


def test_concurrent_posts_single_job(local):
    store,admin,users,cfg=local
    key=str(uuid4())
    with ThreadPoolExecutor(2) as pool:
        rows=list(pool.map(lambda _:enqueue(store,users[0],cfg,key),range(2)))
    assert rows[0]['id']==rows[1]['id']
    with pytest.raises(JobError,match='quota_exceeded'):
        enqueue(store,users[0],cfg)


def test_claim_lease_recovery_and_fencing(local):
    store,admin,users,cfg=local
    row=enqueue(store,users[0],cfg)
    with ThreadPoolExecutor(2) as pool:
        claimed=list(pool.map(lambda _:store.claim(uuid4()),range(2)))
    assert sum(c is not None for c in claimed)==1
    old=next(c for c in claimed if c)
    store.put_artifact(old,'owned',data={'ok':True})
    admin.execute("update foodiefy_imports.jobs set lease_until=now()-interval '1 second' where id=%s",(row['id'],))
    new=store.claim(uuid4())
    assert new['fencing_token']==old['fencing_token']+1
    assert store.artifact(new,'owned')['data']=={'ok':True}
    for action in [lambda:store.checkpoint(old),lambda:store.finish(old,'succeeded'),lambda:store.put_artifact(old,'owned',data={'stale':True})]:
        with pytest.raises(JobError,match='lease_lost'):
            action()


def test_budget_reservations_atomic_across_workers(local):
    store,admin,users,cfg=local
    admin.execute('update foodiefy_imports.controls set worker_concurrency=2,global_usd=0.015')
    for user in users:
        enqueue(store,user,cfg)
    jobs=[store.claim(uuid4()),store.claim(uuid4())]
    def reserve(job):
        try:
            return store.reserve(job,'stt','stt','openai','gpt-transcribe',.01,'test')['id']
        except JobError as exc:
            return exc.code
    with ThreadPoolExecutor(2) as pool:
        results=list(pool.map(reserve,jobs))
    assert results.count('budget_exhausted')==1
    total=admin.execute('select sum(reserved_usd) as n from foodiefy_imports.usage_ledger where owner_id=any(%s)',(users,)).fetchone()['n']
    assert float(total)==.01


def test_cancel_cleans_artifacts_and_fences_inflight(local):
    store,admin,users,cfg=local
    row=enqueue(store,users[0],cfg)
    job=store.claim(uuid4())
    store.put_artifact(job,'audio',blob=b'own-test')
    entry=store.reserve(job,'stt','stt','openai','gpt-transcribe',.01,'test')
    store.cancel(users[0],row['id'])
    with pytest.raises(JobError,match='lease_lost'):
        store.settle(job,entry,data={'text':'late'},usage={'cost_estimate':.01})
    assert admin.execute('select count(*) as n from foodiefy_imports.artifacts where job_id=%s',(row['id'],)).fetchone()['n']==0
    assert admin.execute('select state from foodiefy_imports.usage_ledger where id=%s',(entry['id'],)).fetchone()['state']=='uncertain'


def test_private_cache_source_hash_policy_and_owner(local):
    store,admin,users,cfg=local
    enqueue(store,users[0],cfg)
    claimed=store.claim(uuid4())
    store.cache(claimed,'content-A',{'sample':'owned'})
    assert store.cache(claimed,'content-A')=={'sample':'owned'}
    assert store.cache(claimed,'content-B') is None
    store.finish(claimed,'succeeded')
    enqueue(store,users[1],cfg)
    other=store.claim(uuid4())
    assert store.cache(other,'content-A') is None


def test_rls_and_composite_artifact_ownership(local):
    store,admin,users,cfg=local
    row=enqueue(store,users[0],cfg)
    with psycopg.connect(cfg.IMPORT_DATABASE_URL.get_secret_value()) as conn:
        conn.execute('set local role authenticated')
        conn.execute("select set_config('request.jwt.claim.sub',%s,true)",(str(users[1]),))
        assert conn.execute('select count(*) from foodiefy_imports.jobs where id=%s',(row['id'],)).fetchone()[0]==0
        conn.execute("select set_config('request.jwt.claim.sub',%s,true)",(str(users[0]),))
        assert conn.execute('select count(*) from foodiefy_imports.jobs where id=%s',(row['id'],)).fetchone()[0]==1
        with pytest.raises(psycopg.errors.InsufficientPrivilege):
            conn.execute("update foodiefy_imports.jobs set status='succeeded' where id=%s",(row['id'],))
    with pytest.raises(psycopg.errors.ForeignKeyViolation):
        admin.execute("insert into foodiefy_imports.artifacts(job_id,owner_id,artifact_key,content_hash,data,expires_at) values(%s,%s,'wrong',repeat('a',64),'{}',now()+interval '1 day')",(row['id'],users[1]))


def worker_fakes(local,tmp_path,*,visual=False):
    store,admin,users,cfg=local
    cfg=cfg.model_copy(update={'ENABLE_VISUAL_FALLBACK':visual})
    counts={'source':0,'media':0,'stt':0,'extract':0}
    b=EvidenceBundle(canonical_url='https://example.org/owned-test',platform='youtube',source_type='social_video')
    b.description=fragment('description','cantidades en pantalla' if visual else 'Mezclar ingredientes')
    b=finalize(b)
    ref=EvidenceBundle(canonical_url='https://example.org',platform='web',source_type='webpage')
    parse_html((Path(__file__).parent/'fixtures/acquisition/simple.html').read_bytes(),ref)
    answer=direct_json_ld(ref)
    class Resolver:
        def __init__(self,**kw): self.stage=kw['on_stage']
        def resolve(self,url):
            counts['source']+=1
            self.stage('extracting_metadata')
            return b
    class Media:
        def __init__(self,*a,**kw): pass
        @contextmanager
        def audio(self,evidence):
            counts['media']+=1
            path=tmp_path/'owned.mp3'
            path.write_bytes(b'ID3-owned-synthetic-test')
            try:
                yield AudioEvidence(path,2)
            finally:
                path.unlink(missing_ok=True)
    class STT:
        def __init__(self,config,session): self.session=session
        def transcribe(self,evidence):
            def invoke():
                counts['stt']+=1
                return {'text':'Mezclar'},StageUsage(stage='stt',provider='openai',model='gpt-transcribe',latency_ms=1,duration_seconds=2)
            data=self.session.execute('stt','openai','gpt-transcribe',.001,invoke)
            return TranscriptResult(text=data['text'],languages=['es'],duration_seconds=2,mime_type='audio/mpeg',size_bytes=10,content_hash='owned',usage=self.session.stages[-1])
    class Extract:
        def __init__(self,config,session,stage): self.session,self.stage=session,stage
        def extract(self,evidence):
            assert evidence.transcript is not None
            assert evidence.bundle.description.text==b.description.text
            def invoke():
                counts['extract']+=1
                if counts['extract']==1:
                    raise PipelineError('provider_transient_error',transient=True)
                result=answer.model_copy(deep=True)
                if visual:
                    result=partial('missing_visual')
                    result.visual_evidence_required=True
                    result.visual_evidence_reasons=['on_screen_quantities']
                return result.model_dump(mode='json'),StageUsage(stage=self.stage,provider='openai',model='gpt-5-nano',latency_ms=1,input_tokens=10,output_tokens=10)
            data=self.session.execute(self.stage,'openai','gpt-5-nano',.001,invoke)
            return type(answer).model_validate(data)
    return cfg,counts,dict(resolver_factory=Resolver,media_factory=Media,transcriber_factory=STT,extractor_factory=Extract)


def test_stt_persisted_after_extractor_failure_reused_on_new_worker(local,tmp_path):
    store,admin,users,_=local
    cfg,counts,factories=worker_fakes(local,tmp_path)
    row=enqueue(store,users[0],cfg)
    assert Worker(cfg,**factories).run_once()
    assert store.get(users[0],row['id'])['status']=='queued'
    assert counts['stt']==1 and counts['extract']==1
    admin.execute('update foodiefy_imports.jobs set next_attempt_at=now() where id=%s',(row['id'],))
    assert Worker(cfg,**factories).run_once()
    assert store.get(users[0],row['id'])['status']=='succeeded'
    assert counts=={'source':1,'media':1,'stt':1,'extract':2}
    entries=admin.execute('select operation,count(*) as n from foodiefy_imports.usage_ledger where job_id=%s group by operation',(row['id'],)).fetchall()
    assert {r['operation']:r['n'] for r in entries}=={'source':1,'stt':1,'text_extraction':2}
    assert admin.execute('select count(*) as n from foodiefy_imports.artifacts where job_id=%s',(row['id'],)).fetchone()['n']==0


def test_visual_quota_exhausted_never_recharges_stt(local,tmp_path):
    store,admin,users,_=local
    cfg,counts,factories=worker_fakes(local,tmp_path,visual=True)
    # Exercise SQL quota directly after successful STT and cached transcript.
    row=enqueue(store,users[0],cfg)
    Worker(cfg,**factories).run_once()
    admin.execute('update foodiefy_imports.controls set daily_visual=0')
    admin.execute('update foodiefy_imports.jobs set next_attempt_at=now() where id=%s',(row['id'],))
    class VisualMedia(factories['media_factory']):
        @contextmanager
        def visual(self,evidence):
            from src.analysis.models import VisualEvidence
            path=tmp_path/'owned-frame.jpg'
            path.write_bytes(b'owned-test-not-provider-input')
            try:
                yield VisualEvidence(evidence,(path,),'frames',2,(0,))
            finally:
                path.unlink(missing_ok=True)
    class Visual:
        def __init__(self,config,session):
            self.session=session
        def extract(self,evidence):
            return self.session.execute('visual','gemini','gemini-2.5-flash',.001,lambda:pytest.fail('visual provider must not be called'))
    factories['visual_factory']=Visual
    factories['media_factory']=VisualMedia
    Worker(cfg,**factories).run_once()
    result=store.get(users[0],row['id'])
    assert result['error_code']=='visual_required_unavailable'
    assert counts['stt']==1
    assert admin.execute("select count(*) as n from foodiefy_imports.usage_ledger where job_id=%s and operation='stt'",(row['id'],)).fetchone()['n']==1


def test_uncertain_call_not_replayed_after_lease_loss(local):
    store,admin,users,cfg=local
    enqueue(store,users[0],cfg)
    old=store.claim(uuid4())
    store.reserve(old,'stt','stt','openai','gpt-transcribe',.001,'test')
    admin.execute("update foodiefy_imports.jobs set lease_until=now()-interval '1 second' where id=%s",(old['id'],))
    new=store.claim(uuid4())
    s=DurableSession(store,new,cfg)
    with pytest.raises(PipelineError,match='provider_down'):
        s.execute('stt','openai','gpt-transcribe',.001,lambda:pytest.fail('would repay uncertain call'))


def test_paid_response_survives_crash_before_typed_artifact(local):
    store,admin,users,cfg=local
    enqueue(store,users[0],cfg)
    old=store.claim(uuid4())
    entry=store.reserve(old,'stt','stt','openai','gpt-transcribe',.001,'test')
    usage=StageUsage(stage='stt',provider='openai',model='gpt-transcribe',latency_ms=1,cost_estimate=.001)
    store.settle(old,entry,data={'text':'persisted'},usage=usage.model_dump(mode='json'))
    admin.execute("update foodiefy_imports.jobs set lease_until=now()-interval '1 second' where id=%s",(old['id'],))
    new=store.claim(uuid4())
    s=DurableSession(store,new,cfg)
    assert s.execute('stt','openai','gpt-transcribe',.001,lambda:pytest.fail('repay'))=={'text':'persisted'}
    admin.execute("update foodiefy_imports.artifacts set data='{}' where job_id=%s",(new['id'],))
    with pytest.raises(PipelineError,match='invalid_output'):
        s.execute('stt','openai','gpt-transcribe',.001,lambda:pytest.fail('corrupt STT repaid'))


def test_source_recovery_is_retryable_without_paid_replay(local):
    store,admin,users,cfg=local
    enqueue(store,users[0],cfg)
    old=store.claim(uuid4())
    store.reserve(old,'source','source','http','source-resolver-v1',0,'no-ai-charge')
    admin.execute("update foodiefy_imports.jobs set lease_until=now()-interval '1 second' where id=%s",(old['id'],))
    new=store.claim(uuid4())
    replay=store.reserve(new,'source','source','http','source-resolver-v1',0,'no-ai-charge')
    assert replay['attempt']==2 and replay['reserved_usd']==0


def test_kill_switches_and_output_size(local):
    store,admin,users,cfg=local
    enqueue(store,users[0],cfg)
    job=store.claim(uuid4())
    admin.execute('update foodiefy_imports.controls set enabled=false')
    with pytest.raises(JobError,match='canceled'):
        store.checkpoint(job,'transcribing')
    admin.execute('update foodiefy_imports.controls set enabled=true,visual_enabled=false,output_bytes=1024')
    with pytest.raises(JobError,match='visual_required_unavailable'):
        store.checkpoint(job,'analyzing_visual_evidence',visual=True)
    store.finish(job,'succeeded',result={'too_large':'x'*2048})
    assert store.get(users[0],job['id'])['error_code']=='invalid_output'


def test_pagination_owned_stable_cursor(local):
    store,admin,users,cfg=local
    for _ in range(3):
        row=enqueue(store,users[0],cfg)
        store.cancel(users[0],row['id'])
    first,cursor=store.list(users[0],2,None)
    second,tail=store.list(users[0],2,cursor)
    assert len(first)==2 and len(second)==1 and tail is None
    assert not ({r['id'] for r in first}&{r['id'] for r in second})
    assert store.list(users[1],2,cursor)==([],None)
